frappe.pages['items-manager'].on_page_load = function(wrapper) {
    frappe.ui.make_app_page({
        parent: wrapper,
        title: 'Items Manager',
        single_column: true,
    });

    new ItemsManager(wrapper);
};

class ItemsManager {
    constructor(wrapper) {
        this.wrapper = wrapper;
        this.page = wrapper.page;
        this.$body = $(wrapper).find('.layout-main-section');
        this.job_id = null;
        this.poll_interval = null;
        this.render();
    }

    render() {
        this.$body.html(`
            <div class="items-manager">
                <ul class="nav nav-tabs" style="margin-bottom: 16px;">
                    <li class="nav-item">
                        <a class="nav-link active" data-tab="import" href="#">Import</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-tab="items" href="#">Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-tab="review" href="#">Review Queue</a>
                    </li>
                </ul>
                <div id="tab-import"></div>
                <div id="tab-items" style="display:none;"></div>
                <div id="tab-review" style="display:none;"></div>
            </div>
        `);

        this.$body.on('click', '.nav-link', (e) => {
            e.preventDefault();
            const tab = $(e.currentTarget).data('tab');
            this.switch_tab(tab);
        });

        this.render_import_tab();
    }

    switch_tab(tab) {
        this.$body.find('.nav-link').removeClass('active');
        this.$body.find(`.nav-link[data-tab="${tab}"]`).addClass('active');
        this.$body.find('#tab-import, #tab-items, #tab-review').hide();
        this.$body.find(`#tab-${tab}`).show();

        if (tab === 'items') this.load_items();
        if (tab === 'review') this.load_review_queue();
    }

    // ─── TAB 1: IMPORT ───────────────────────────────────────────────────────

    render_import_tab() {
        this.$body.find('#tab-import').html(`
            <div style="max-width: 700px;">
                <h5>Upload Item Master CSV</h5>
                <p class="text-muted">Upload the <code>item_master.csv</code> file generated by the pipeline.</p>

                <div class="form-group">
                    <input type="file" id="csv-file-input" accept=".csv" class="form-control">
                </div>
                <button id="btn-check" class="btn btn-secondary btn-sm" style="margin-right:8px;">
                    Check
                </button>
                <button id="btn-import" class="btn btn-primary btn-sm" disabled>
                    Import
                </button>

                <div id="preflight-report" style="margin-top: 16px;"></div>
                <div id="import-progress" style="margin-top: 16px; display:none;">
                    <div class="progress">
                        <div id="progress-bar" class="progress-bar" style="width:0%"></div>
                    </div>
                    <p id="progress-label" class="text-muted" style="margin-top:4px;">Starting...</p>
                </div>
                <div id="import-results" style="margin-top: 16px;"></div>
            </div>
        `);

        this.$body.find('#btn-check').on('click', () => this.run_preflight());
        this.$body.find('#btn-import').on('click', () => this.start_import());
    }

    get_file_content() {
        return new Promise((resolve, reject) => {
            const file = document.getElementById('csv-file-input').files[0];
            if (!file) {
                frappe.msgprint('Please select a CSV file first.');
                reject();
                return;
            }
            const reader = new FileReader();
            reader.onload = e => resolve(e.target.result);
            reader.onerror = reject;
            reader.readAsText(file);
        });
    }

    run_preflight() {
        this.get_file_content().then(content => {
            this.$body.find('#preflight-report').html(
                '<p class="text-muted">Checking...</p>'
            );
            frappe.call({
                method: 'items.api.validate_csv',
                args: { file_content: content },
                callback: r => this.render_preflight(r.message),
                error: () => {
                    this.$body.find('#preflight-report').html(
                        '<div class="alert alert-danger">Could not parse CSV — ensure this is pipeline output (item_master.csv).</div>'
                    );
                }
            });
        }).catch(() => {});
    }

    render_preflight(result) {
        const m = result.missing;
        const has_issues = m.item_groups.length || m.uoms.length || m.suppliers.length;

        let html = `<div class="alert alert-${has_issues ? 'warning' : 'success'}">`;
        html += `<strong>${result.ready} items ready to import.</strong>`;

        if (has_issues) {
            html += '<br><br><strong>Missing dependencies (create these in ERPNext first):</strong><ul>';
            if (m.item_groups.length) html += `<li>Item Groups: ${m.item_groups.join(', ')}</li>`;
            if (m.uoms.length) html += `<li>UOMs: ${m.uoms.join(', ')}</li>`;
            if (m.suppliers.length) html += `<li>Suppliers: ${m.suppliers.join(', ')}</li>`;
            html += '</ul>';
        }
        html += '</div>';

        this.$body.find('#preflight-report').html(html);
        this.$body.find('#btn-import').prop('disabled', !!has_issues);
    }

    start_import() {
        this.get_file_content().then(content => {
            this.$body.find('#btn-import').prop('disabled', true);
            this.$body.find('#btn-check').prop('disabled', true);
            this.$body.find('#import-progress').show();
            this.$body.find('#import-results').html('');

            frappe.call({
                method: 'items.api.enqueue_import',
                args: { file_content: content },
                callback: r => {
                    this.job_id = r.message.job_id;
                    this.poll_progress();
                }
            });
        }).catch(() => {});
    }

    poll_progress() {
        this.poll_interval = setInterval(() => {
            frappe.call({
                method: 'items.api.get_progress',
                args: { job_id: this.job_id },
                callback: r => {
                    const p = r.message;
                    if (!p || p.total === 0) return;

                    const pct = Math.round((p.current / p.total) * 100);
                    this.$body.find('#progress-bar').css('width', pct + '%');
                    this.$body.find('#progress-label').text(
                        `${p.current} / ${p.total} rows processed — ${p.imported} imported, ${p.errors.length} errors`
                    );

                    if (p.current >= p.total) {
                        clearInterval(this.poll_interval);
                        this.render_import_results(p);
                        this.$body.find('#btn-check').prop('disabled', false);
                    }
                }
            });
        }, 2000);
    }

    render_import_results(p) {
        let html = `<div class="alert alert-${p.errors.length ? 'warning' : 'success'}">`;
        html += `<strong>Import complete: ${p.imported} imported`;
        if (p.errors.length) html += `, ${p.errors.length} skipped with errors`;
        html += '</strong>';

        if (p.errors.length) {
            html += '<details style="margin-top:8px;"><summary>Show errors</summary><ul style="margin-top:8px;">';
            p.errors.forEach(e => {
                html += `<li>Row ${e.row} — <code>${e.item_code}</code>: ${e.error}</li>`;
            });
            html += '</ul></details>';
        }
        html += '</div>';

        this.$body.find('#import-progress').hide();
        this.$body.find('#import-results').html(html);
        this.$body.find('#btn-import').prop('disabled', false);
    }

    // ─── TAB 2: ITEMS ─────────────────────────────────────────────────────────

    load_items(page = 1) {
        const search = this.$body.find('#item-search').val() || '';
        const group = this.$body.find('#item-group-filter').val() || '';
        this.current_page = page;

        frappe.call({
            method: 'items.api.get_items',
            args: { search, item_group: group, page, page_size: 50 },
            callback: r => this.render_items_table(r.message),
        });
    }

    render_items_tab_shell() {
        this.$body.find('#tab-items').html(`
            <div style="max-width: 900px;">
                <div style="display:flex; gap:8px; margin-bottom:12px; align-items:center;">
                    <input id="item-search" type="text" class="form-control form-control-sm"
                           placeholder="Search items..." style="max-width:240px;">
                    <select id="item-group-filter" class="form-control form-control-sm" style="max-width:160px;">
                        <option value="">All Groups</option>
                        <option value="Part">Part</option>
                        <option value="Material">Material</option>
                        <option value="Service">Service</option>
                    </select>
                    <button id="btn-delete-selected" class="btn btn-danger btn-sm" disabled>
                        Delete Selected
                    </button>
                    <button id="btn-delete-all" class="btn btn-outline-danger btn-sm">
                        Delete All
                    </button>
                </div>
                <div id="items-table-container"></div>
                <div id="items-pagination" style="margin-top:12px;"></div>
            </div>
        `);

        let search_timer;
        this.$body.find('#item-search, #item-group-filter').on('input change', () => {
            clearTimeout(search_timer);
            search_timer = setTimeout(() => this.load_items(1), 300);
        });

        this.$body.find('#btn-delete-selected').on('click', () => this.delete_selected());
        this.$body.find('#btn-delete-all').on('click', () => this.confirm_delete_all());
    }

    render_items_table(data) {
        if (!this.$body.find('#items-table-container').length) {
            this.render_items_tab_shell();
        }

        const rows_html = data.items.map(item => `
            <tr>
                <td><input type="checkbox" class="item-checkbox" data-name="${item.name}"></td>
                <td>${frappe.utils.escape_html(item.item_code || item.name)}</td>
                <td>${frappe.utils.escape_html(item.item_name)}</td>
                <td>${frappe.utils.escape_html(item.item_group)}</td>
                <td>${frappe.utils.escape_html(item.stock_uom)}</td>
                <td>${frappe.utils.escape_html(item.supplier || '')}</td>
            </tr>
        `).join('');

        this.$body.find('#items-table-container').html(`
            <table class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th style="width:32px;">
                            <input type="checkbox" id="select-all-items">
                        </th>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Group</th>
                        <th>UOM</th>
                        <th>Supplier</th>
                    </tr>
                </thead>
                <tbody>${rows_html}</tbody>
            </table>
            <p class="text-muted">${data.total} total items</p>
        `);

        // Pagination
        const total_pages = Math.ceil(data.total / 50);
        const cur = this.current_page || 1;
        this.$body.find('#items-pagination').html(`
            <button class="btn btn-sm btn-secondary" id="btn-prev-page" ${cur <= 1 ? 'disabled' : ''}>
                ← Prev
            </button>
            <span style="margin: 0 12px;">Page ${cur} of ${total_pages}</span>
            <button class="btn btn-sm btn-secondary" id="btn-next-page" ${cur >= total_pages ? 'disabled' : ''}>
                Next →
            </button>
        `);

        this.$body.find('#btn-prev-page').on('click', () => this.load_items(cur - 1));
        this.$body.find('#btn-next-page').on('click', () => this.load_items(cur + 1));

        // Checkbox events
        this.$body.find('#select-all-items').on('change', (e) => {
            this.$body.find('.item-checkbox').prop('checked', e.target.checked);
            this.update_delete_selected_btn();
        });
        this.$body.find('.item-checkbox').on('change', () => this.update_delete_selected_btn());
    }

    update_delete_selected_btn() {
        const count = this.$body.find('.item-checkbox:checked').length;
        this.$body.find('#btn-delete-selected').prop('disabled', count === 0)
            .text(count ? `Delete Selected (${count})` : 'Delete Selected');
    }

    delete_selected() {
        const codes = this.$body.find('.item-checkbox:checked')
            .map((_, el) => $(el).data('name')).get();
        if (!codes.length) return;

        frappe.confirm(
            `Delete ${codes.length} selected item(s)? This cannot be undone.`,
            () => this.do_delete({ item_codes: codes })
        );
    }

    confirm_delete_all() {
        let d = new frappe.ui.Dialog({
            title: 'Delete All Items',
            fields: [{
                fieldname: 'confirm_text',
                fieldtype: 'Data',
                label: 'Type CONFIRM to delete all items',
            }],
            primary_action_label: 'Delete All',
            primary_action(values) {
                if (values.confirm_text !== 'CONFIRM') {
                    frappe.msgprint('Please type CONFIRM exactly.');
                    return;
                }
                d.hide();
                this.do_delete({ delete_all: true });
            }.bind(this),
        });
        d.show();
    }

    do_delete(args) {
        frappe.call({
            method: 'items.api.delete_items',
            args,
            callback: r => {
                const res = r.message;
                if (res.error) {
                    frappe.msgprint({
                        title: 'Cannot Delete',
                        message: res.error + '<br>Protected: ' + res.protected.join(', '),
                        indicator: 'red',
                    });
                } else {
                    frappe.show_alert({
                        message: `${res.deleted} item(s) deleted`,
                        indicator: 'green',
                    });
                    this.load_items(1);
                }
            }
        });
    }

    // ─── TAB 3: REVIEW QUEUE ─────────────────────────────────────────────────

    load_review_queue() {
        this.$body.find('#tab-review').html('<p class="text-muted">Loading...</p>');
        frappe.call({
            method: 'items.api.get_review_queue',
            callback: r => {
                const res = r.message;
                if (res.error) {
                    this.$body.find('#tab-review').html(
                        `<div class="alert alert-warning">${res.error}</div>`
                    );
                } else {
                    this.render_review_queue(res.rows);
                }
            },
        });
    }

    render_review_queue(rows) {
        const badge_color = { HIGH: 'red', MEDIUM: 'orange', LOW: 'grey' };

        const rows_html = rows.map(row => {
            const color = badge_color[row.priority] || 'grey';
            const erpnext_link = row.exists_in_erpnext
                ? `<a href="/app/item/${encodeURIComponent(row.item_code)}" target="_blank">Open ↗</a>`
                : '<span class="text-muted">—</span>';

            return `
                <tr>
                    <td>${frappe.utils.escape_html(row.item_name)}</td>
                    <td>${frappe.utils.escape_html(row.item_group)}</td>
                    <td>${frappe.utils.escape_html(row.stock_uom)}</td>
                    <td style="font-size:0.85em;">${frappe.utils.escape_html(row.flag_reasons)}</td>
                    <td style="font-size:0.85em;">${frappe.utils.escape_html(row.suggested_action)}</td>
                    <td>
                        <span class="indicator-pill" style="background:${color}; color:white; padding:2px 8px; border-radius:10px;">
                            ${row.priority}
                        </span>
                    </td>
                    <td>${erpnext_link}</td>
                </tr>
            `;
        }).join('');

        this.$body.find('#tab-review').html(`
            <div style="max-width: 1000px;">
                <p class="text-muted">${rows.length} items flagged for review</p>
                <table class="table table-sm table-bordered">
                    <thead>
                        <tr>
                            <th>Item Name</th>
                            <th>Group</th>
                            <th>UOM</th>
                            <th>Flag Reasons</th>
                            <th>Suggested Action</th>
                            <th>Priority</th>
                            <th>ERPNext</th>
                        </tr>
                    </thead>
                    <tbody>${rows_html}</tbody>
                </table>
            </div>
        `);
    }
}
